/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Terminkalender.GUIPart;

import Terminkalender.Anfrage;
import Terminkalender.BenutzerException;

import javax.swing.DefaultListModel;
import java.awt.*;
import Terminkalender.LauncherInterface;
import Terminkalender.Teilnehmer;
import Terminkalender.TerminException;
import java.awt.event.WindowEvent;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author med
 */
public class EventDet extends javax.swing.JFrame {
    
    private final LauncherInterface stub;
    private final int sitzungsID;
    private final int index;
    String eventText;
    Hauptfenster hauptfenster;

    
    /**
     * Create new event
     * @param event
     * @param stub
     * @param sitzungsID
     * @param index
     * @param hauptfenster
     */
    public EventDet(String event, LauncherInterface stub, int sitzungsID, int index, Hauptfenster hauptfenster) {
        this.stub=stub;
        this.sitzungsID = sitzungsID;
        this.eventText = event;
        this.index = index;
        this.hauptfenster = hauptfenster;
        
        initComponents();
        eventLabel.setText(eventText);      
    }

    public void terminAblehnen() throws RemoteException, BenutzerException, TerminException, SQLException {
        stub.terminAblehnen(((Anfrage) stub.getMeldungen(sitzungsID).get(index)).getTermin().getID(), sitzungsID);
    }
    
    /**
     *methode zum schliessen von vorherige fenster
     */
    public void fensterClose(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        eventLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        annehmenButton = new javax.swing.JButton();
        loeschenButton = new javax.swing.JButton();
        ablehnenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Benachrichtigung Event");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(29, 30, 66));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(46, 49, 117));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eventLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        eventLabel.setForeground(new java.awt.Color(240, 240, 240));
        jPanel3.add(eventLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 460, 160));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Nachricht");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 484, 220));

        annehmenButton.setBackground(new java.awt.Color(46, 49, 117));
        annehmenButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        annehmenButton.setForeground(new java.awt.Color(240, 240, 240));
        annehmenButton.setText("Annehmen");
        annehmenButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        annehmenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annehmenButtonActionPerformed(evt);
            }
        });
        jPanel2.add(annehmenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 130, 40));

        loeschenButton.setBackground(new java.awt.Color(46, 49, 117));
        loeschenButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loeschenButton.setForeground(new java.awt.Color(240, 240, 240));
        loeschenButton.setText("Löschen");
        loeschenButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loeschenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loeschenButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loeschenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 120, 40));

        ablehnenButton.setBackground(new java.awt.Color(46, 49, 117));
        ablehnenButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ablehnenButton.setForeground(new java.awt.Color(240, 240, 240));
        ablehnenButton.setText("Ablehnen");
        ablehnenButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ablehnenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ablehnenButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ablehnenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void annehmenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annehmenButtonActionPerformed
        // TODO add your handling code here:
        try {
            Anfrage anfrage = (Anfrage) stub.getMeldungen(sitzungsID).get(index);
            boolean check = false;
            
            try{
                stub.getTermin(anfrage.getTermin().getID(), sitzungsID);
   
            } catch (RemoteException | BenutzerException | TerminException ex) {
                JOptionPane.showMessageDialog(null, "Termin wurde bereits abgelehnt");
                check = true;
            }
            if(!check){
               check = false;
               for(Teilnehmer teilnehmer : anfrage.getTermin().getTeilnehmerliste()){
                    if(teilnehmer.getUsername().equals(stub.getUsername(sitzungsID)) && teilnehmer.checkIstTeilnehmer()){
                        JOptionPane.showMessageDialog(null, "Termin wurde bereits angenommen");
                        check = true;
                    }
                }
                
                if(!check){
                    stub.terminAnnehmen(anfrage.getTermin().getID(), sitzungsID);
                    JOptionPane.showMessageDialog(null, "Einladung wurde Angennomen");
                } 
            }
            dispose();     
        } catch (TerminException | SQLException | RemoteException | BenutzerException ex) {
            Logger.getLogger(EventDet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_annehmenButtonActionPerformed

    private void ablehnenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ablehnenButtonActionPerformed
        // TODO add your handling code here:
        try {
            Anfrage anfrage = (Anfrage) stub.getMeldungen(sitzungsID).get(index);
            boolean check = false;
            
            try{
                stub.getTermin(anfrage.getTermin().getID(), sitzungsID);     
            } catch (RemoteException | BenutzerException | TerminException ex) {
                JOptionPane.showMessageDialog(null, "Termin wurde bereits abgelehnt");
                check = true;
            }
            if(!check){
                check = false;
                for(Teilnehmer teilnehmer : anfrage.getTermin().getTeilnehmerliste()){
                    if(teilnehmer.getUsername().equals(stub.getUsername(sitzungsID)) && teilnehmer.checkIstTeilnehmer()){
                        JOptionPane.showMessageDialog(null, "Termin wurde bereits angenommen");
                        check = true;
                    }
                }
                
                if(!check){
                    terminAblehnen();
                    hauptfenster.displayDate();
                    JOptionPane.showMessageDialog(null, "Einladung wurde Abgelehnt");
                } 
            }
            dispose(); 
        } catch (SQLException | RemoteException | BenutzerException | TerminException ex) {
            Logger.getLogger(EventDet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ablehnenButtonActionPerformed

    private void loeschenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loeschenButtonActionPerformed
        // TODO add your handling code here:
        try {
            Anfrage anfrage = (Anfrage) stub.getMeldungen(sitzungsID).get(index);
            boolean nochOffen = true;
            
            try{
                stub.getTermin(anfrage.getTermin().getID(), sitzungsID);  
                for(Teilnehmer teilnehmer : anfrage.getTermin().getTeilnehmerliste()){
                    if(teilnehmer.getUsername().equals(stub.getUsername(sitzungsID)) && teilnehmer.checkIstTeilnehmer()){
                        stub.deleteMeldung(index , sitzungsID);
                        hauptfenster.fillMeldList();
                        JOptionPane.showMessageDialog(null, "Deine Benachrichtigung Wurde gelöscht");
                        nochOffen = false;
                    }
                }   
            } catch (RemoteException | BenutzerException | TerminException ex) {
                stub.deleteMeldung(index , sitzungsID);
                hauptfenster.fillMeldList();
                JOptionPane.showMessageDialog(null, "Deine Benachrichtigung Wurde gelöscht");
                nochOffen = false;
            }
            
            if(nochOffen){
                JOptionPane.showMessageDialog(null, "Meldung kann erst gelöscht werden, nachdem der Termin angenommen oder abgelehnt wurde");
            } 
            dispose();
            
        } catch (RemoteException | BenutzerException | SQLException ex) {
            Logger.getLogger(EventDet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loeschenButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventDet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventDet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventDet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventDet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EventDet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ablehnenButton;
    private javax.swing.JButton annehmenButton;
    private javax.swing.JLabel eventLabel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loeschenButton;
    // End of variables declaration//GEN-END:variables
}
