/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Terminkalender.GUIPart;

import Terminkalender.BenutzerException;
import Terminkalender.LauncherInterface;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author niroshan
 */
public class Registrieren extends javax.swing.JFrame {

    private final LauncherInterface stub;

    /**
     * Creates new form Registrieren
     *
     * @param stub
     */
    public Registrieren(LauncherInterface stub) {
        initComponents();
        this.stub = stub;
    }

    private Registrieren() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void zuweisen(String username, String password, String email) throws RemoteException, SQLException {

        boolean wiederholen = false;

        try {
            stub.createUser(username, password, email);
            JOptionPane.showMessageDialog(null, "Registrierung erfolgreich", "Registrieren", JOptionPane.INFORMATION_MESSAGE);
            
            regUsername.setText(null);
            regPassword.setText(null);
            regEmail.setText(null);

            this.setVisible(false);
            
        } catch (BenutzerException e) {
            //JOptionPane.showInputDialog();
            JOptionPane.showMessageDialog(null,e.getMessage(), "Registrieren", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        regUsername = new javax.swing.JLabel();
        regUsernameField = new javax.swing.JTextField();
        regPassword = new javax.swing.JLabel();
        regPasswordField = new javax.swing.JPasswordField();
        regEmail = new javax.swing.JLabel();
        regEmailField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        regButton = new javax.swing.JButton();
        abbrButton = new javax.swing.JButton();

        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(29, 30, 66));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        regUsername.setForeground(new java.awt.Color(240, 240, 240));
        regUsername.setText("Benutzername");
        jPanel2.add(regUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        regUsernameField.setBackground(new java.awt.Color(29, 30, 66));
        regUsernameField.setForeground(new java.awt.Color(240, 240, 240));
        regUsernameField.setBorder(null);
        jPanel2.add(regUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 128, -1));

        regPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        regPassword.setForeground(new java.awt.Color(240, 240, 240));
        regPassword.setText("Passwort");
        jPanel2.add(regPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        regPasswordField.setBackground(new java.awt.Color(29, 30, 66));
        regPasswordField.setForeground(new java.awt.Color(240, 240, 240));
        regPasswordField.setBorder(null);
        jPanel2.add(regPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 128, -1));

        regEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        regEmail.setForeground(new java.awt.Color(240, 240, 240));
        regEmail.setText("E-mail Adresse");
        jPanel2.add(regEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        regEmailField.setBackground(new java.awt.Color(29, 30, 66));
        regEmailField.setForeground(new java.awt.Color(240, 240, 240));
        regEmailField.setBorder(null);
        jPanel2.add(regEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 128, -1));

        jPanel3.setBackground(new java.awt.Color(46, 49, 117));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Registriereung");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Terminkalender/GUIPart/if_Account_1891016.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 130, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 220, 270));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 160, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 160, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 160, 10));

        regButton.setBackground(new java.awt.Color(46, 49, 117));
        regButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        regButton.setForeground(new java.awt.Color(240, 240, 240));
        regButton.setText("Registrieren");
        regButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });
        jPanel2.add(regButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 130, 30));

        abbrButton.setBackground(new java.awt.Color(46, 49, 117));
        abbrButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        abbrButton.setForeground(new java.awt.Color(240, 240, 240));
        abbrButton.setText("Abbrechen");
        abbrButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        abbrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abbrButtonActionPerformed(evt);
            }
        });
        jPanel2.add(abbrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abbrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abbrButtonActionPerformed
        // TODO add your handling code here:
        regUsername.setText(null);
        regPassword.setText(null);
        regEmail.setText(null);

        this.setVisible(false);
    }//GEN-LAST:event_abbrButtonActionPerformed

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        // TODO add your handling code here:
        String username, password, email;

        username = this.regUsernameField.getText();

        password = this.regPasswordField.getText();

        email = this.regEmailField.getText();

        try {
            this.zuweisen(username, password, email);
        } catch (RemoteException e) {
            JOptionPane.showInputDialog(e.getMessage());
        }
        catch (SQLException ex) {
            Logger.getLogger(Registrieren.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_regButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrieren.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrieren.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrieren.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrieren.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrieren().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abbrButton;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton regButton;
    private javax.swing.JLabel regEmail;
    private javax.swing.JTextField regEmailField;
    private javax.swing.JLabel regPassword;
    private javax.swing.JPasswordField regPasswordField;
    private javax.swing.JLabel regUsername;
    private javax.swing.JTextField regUsernameField;
    // End of variables declaration//GEN-END:variables
}
